.TH "C:/My Programs/Name Sorter/Name Sorter/obj/Debug/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs" 3 "Name Sorter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/My Programs/Name Sorter/Name Sorter/obj/Debug/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Name Sorter from the source code\&.
