.TH "C:/My Programs/Name Sorter/Name Sorter/Properties/AssemblyInfo.cs" 3 "Name Sorter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/My Programs/Name Sorter/Name Sorter/Properties/AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Name Sorter from the source code\&.
